### ISSUE TITLE
Having issues trying to remove offline users using the X button 

### ISSUE THREAD

**Issue by prawnz** [BalticAmadeus/ScrumPoker#11]
With regards to #2 
I am having issues trying to remove offline users using the X button as it is not doing anything. 

Any guidance on this?

**Comment by prawnz** [comment]
I think the kick functionality is picking up the wrong user name as shown
![image](https://user-images.githubusercontent.com/3827044/156097981-2eb373ad-6b65-4ad9-a364-819ef9a54891.png)

**Comment by akompanas** [comment]
Thanks for reporting an issue. It's a pleasure to see anyone trying to use this ~~old~~ mature project.

Having said that, I would encourage you to open a pull request and get involved, if that is a suitable option. The last commit is 5 years old now, so either this code does the job extremely well for everybody, or nobody else is using this feature. Either way, the chances of this getting fixed without help are pretty slim.

**Comment by prawnz** [comment]
haha just realised its a "matured" project.  I like the simplicity of yours but i think many got swayed to the advance one. All good..
