### ISSUE TITLE
Use QR code to join the room

### ISSUE THREAD

**Issue by akompanas** [BalticAmadeus/ScrumPoker#4]
Show a QR code in main voting room so that anyone who scans it can join the room directly.

If QR code must be large enough so that it takes too much space, provide a way too zoom it in on the screen on request. E.g. clicking on it will make it full screen with black background.

**Comment by akompanas** [comment]
QR code stops working when deployed to a server. See example at http://ba-sp.azurewebsites.net

**Comment by MantasGaleckas** [comment]
The URL was too long for set QR version. Increased generated QR version, it should support more characters now.
